# Generated by Django 5.1 on 2024-08-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="fuel",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
